# Generated by Django 5.1.4 on 2024-12-10 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_supperadmin',
            new_name='is_superadmin',
        ),
    ]
