# Generated by Django 5.1.4 on 2024-12-20 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menue', '0001_initial'),
        ('vendor', '0004_alter_vendor_modified_at_alter_vendor_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='food_item',
            new_name='FoodItem',
        ),
    ]
