# Generated by Django 5.1.4 on 2024-12-20 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menue', '0002_rename_food_item_fooditem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
    ]
